### ISSUE TITLE
Create @fizz.studio email

### ISSUE THREAD

**Issue by jcdyer** [fizzstudio/fizz#14]
doug@fizz
cliff@fizz

+aliases and lists
admin@
hello@
fizz@

**Comment by shepazu** [comment]
admin@
* alias: help@
* catch-all
* redirect: cliff@, doug@

cliff@
* alias: cliff.dyer@

doug@
* alias: doug.schepers@

hi@
* alias: hello@
* redirect: cliff@, doug@

No lists created yet. Instead of redirects, perhaps we should have admin@ and hi@ as lists. We might later consider adding a list community@, but we don't need that yet.

Closing for now, we can reopen when we need to rethink email.
